### ISSUE TITLE
Batik: org.xml.sax.SAXNotSupportedException

### ISSUE THREAD

**Issue by RuiChen08** [RuiChen08/dacapobench#21]
After updating batik to version 1.9, following error message shows up when running the batik benchmarks:
```
Converting mapWaadt.svg to /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/./scratch/mapWaadt.png ... org.xml.sax.SAXNotSupportedException: Feature: http://xml.org/sax/features/external-general-entities
        at org.apache.crimson.parser.XMLReaderImpl.setFeature(XMLReaderImpl.java:211)
        at org.apache.crimson.jaxp.SAXParserImpl.setFeatures(SAXParserImpl.java:143)
        at org.apache.crimson.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:126)
        at org.apache.crimson.jaxp.SAXParserFactoryImpl.newSAXParserImpl(SAXParserFactoryImpl.java:113)
        at org.apache.crimson.jaxp.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:141)
        at org.apache.batik.dom.util.SAXDocumentFactory.<clinit>(SAXDocumentFactory.java:403)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.createDocumentFactory(SVGAbstractTranscoder.java:150)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:108)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dacapo.harness.Batik.iterate(Batik.java:41)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Harness.main(Unknown Source)
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Feature: http://xml.org/sax/features/external-general-entities
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dacapo.harness.Batik.iterate(Batik.java:41)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Harness.main(Unknown Source)
... error (SVGConverter.error.while.rasterizing.file)
Converting mapSpain.svg to /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/./scratch/mapSpain.png ... org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Feature: http://xml.org/sax/features/external-general-entities
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dacapo.harness.Batik.iterate(Batik.java:41)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Harness.main(Unknown Source)
... error (SVGConverter.error.while.rasterizing.file)
Converting sydney.svg to /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/./scratch/sydney.png ... org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Feature: http://xml.org/sax/features/external-general-entities
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dacapo.harness.Batik.iterate(Batik.java:41)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Harness.main(Unknown Source)
... error (SVGConverter.error.while.rasterizing.file)
```

**Comment by RuiChen08** [comment]
According to the source code of `setFeature` method in Crimson:
```
public void setFeature(String name, boolean state) throws SAXNotRecognizedException, SAXNotSupportedException {
        if (name.equals("http://xml.org/sax/features/namespaces")) {
            this.checkNotParsing("feature", name);
            this.namespaces = state;
            if (!this.namespaces && !this.prefixes) {
                this.prefixes = true;
            }
        } else if (name.equals("http://xml.org/sax/features/namespace-prefixes")) {
            this.checkNotParsing("feature", name);
            this.prefixes = state;
            if (!this.prefixes && !this.namespaces) {
                this.namespaces = true;
            }
        } else if (name.equals("http://xml.org/sax/features/validation")) {
            this.checkNotParsing("feature", name);
            if (this.validation != state) {
                this.parser = null;
            }

            this.validation = state;
        } else {
            if (!name.equals("http://xml.org/sax/features/string-interning")) {
                if (!name.equals("http://xml.org/sax/features/external-general-entities") && !name.equals("http://xml.org/sax/features/external-parameter-entities") && !name.equals("http://xml.org/sax/features/lexical-handler/parameter-entities")) {
                    throw new SAXNotRecognizedException("Feature: " + name);
                }

                throw new SAXNotSupportedException("Feature: " + name);
            }

            if (!state) {
                throw new SAXNotSupportedException("Feature: " + name + " State: false");
            }
        }
```
Obviously, excepting following three links:

* `http://xml.org/sax/features/namespaces`
* `http://xml.org/sax/features/namespace-prefixes`
* `http://xml.org/sax/features/validation`

All other links will somehow cause an exception.

And these links which will cause exceptions are used by `SAXDocumentFactory.java`, see below:
```
     static {
         saxFactory = SAXParserFactory.newInstance();
       try {
            saxFactory.setFeature("http://xml.org/sax/features/external-general-entities", false);
            saxFactory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
            saxFactory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        } catch (SAXNotRecognizedException e) {
            e.printStackTrace();
        } catch (SAXNotSupportedException e) {
            e.printStackTrace();
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
        }
     }
```

Hence, these lines were deleted. And it seems that the program now works correctly. 

Besides, checking the source codes for batik 1.7, and non of the links above was used, check below:
```
            parser.setErrorHandler((errorHandler == null) ?
                                   this : errorHandler);

            parser.setFeature("http://xml.org/sax/features/namespaces",
                              true);
            parser.setFeature("http://xml.org/sax/features/namespace-prefixes",
                              true);
            parser.setFeature("http://xml.org/sax/features/validation",
                              isValidating);
            parser.setProperty("http://xml.org/sax/properties/lexical-handler",
                               this);
            parser.parse(is);
```

But I have not figure out yet the reason why these links were changed. (I will check out the documentations later)

Another possibility is using ` xercesImpl-2.9.1.jar `, which was included by batik. Which is because Apache Xerces replaced Crimson. Check this: https://attic.apache.org/projects/crimson.html

But when I read the documentation for batik, there is a sentence as following:
```
         While the general performance of the Xerces 2.3 parser seems equivalent
         to those of the Crimson parser used previously, there is a notable exception
         in the handling of long attributes. This makes a very visible difference
         for SVG content that uses embeded images through the 'data:' protocol which
         can be extremely slow with Xerces 2.3. The bookOfKells.svgz example, which
         used the data: protocol for rather long images has been removed from the
         distribution as it does not load in a reasonable amount of time when using
         Xerces.
```

**Comment by RuiChen08** [comment]
I roughly looked through the working log of batik project. In this page https://github.com/apache/batik/blame/trunk/batik-dom/src/main/java/org/apache/batik/dom/util/SAXDocumentFactory.java. It mentioned that the reason for adding these links is for resolving a bug:  `BATIK-1139: DTD resolution validation `

Related information could be found in following two pages:
https://issues.apache.org/jira/browse/BATIK-1139
https://issues.apache.org/jira/browse/BATIK-1018

Please check these out, how should we handle it? @johnjiabinzhang

**Comment by johnjiabinzhang** [comment]
I think we can create a patch to comment out the code that seeks to turn off those features. From the links you shared, the reason for the code to be there is because of a potential vulnerability issue. However we are only concerned about measuring the performance with a fixed set of test cases. So we don't need to worry about the vulnerability issues.
