### ISSUE TITLE
h2: broken URL

### ISSUE THREAD

**Issue by johnjiabinzhang** [RuiChen08/dacapobench#3]
The `h2` benchmark has a broken URL issue.
`softlayer.dl.sourceforge.net` has become an unknown host.

```
h2:
     [exec] Buildfile: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/build.xml
     [exec] 
     [exec] incremental:
     [exec] 
     [exec] source:
     [exec] 
     [exec] svn-source:
     [exec] 
     [exec] cvs-source:
     [exec] 
     [exec] clean:
     [exec] 
     [exec] init:
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/build
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/dist
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/dist/harness
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/dist/jar
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/dist/dat
     [exec]     [mkdir] Created dir: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/h2/dist/cnf
     [exec] 
     [exec] unpack:
     [exec] 
     [exec] pre-build:
     [exec] 
     [exec] dacapo-harness:
     [exec] 
     [exec] junit:
     [exec] 
     [exec] url-source:
     [exec] 
     [exec] check-source:
     [exec] 
     [exec] get-source:
     [exec]       [get] Getting: http://softlayer.dl.sourceforge.net/junit/junit4.7.zip
     [exec]       [get] To: /home/johnz/Documents/Work/dacapobench/benchmarks/libs/junit/downloads/junit4.7.zip
     [exec]       [get] Error getting http://softlayer.dl.sourceforge.net/junit/junit4.7.zip to /home/johnz/Documents/Work/dacapobench/benchmarks/libs/junit/downloads/junit4.7.zip
     [exec] 
     [exec] BUILD FAILED
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/bms/common.xml:46: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/libs/libs.xml:83: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/libs/common.xml:24: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/util.xml:31: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/util.xml:50: java.net.UnknownHostException: softlayer.dl.sourceforge.net
     [exec] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
     [exec] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
     [exec] 	at java.net.Socket.connect(Socket.java:589)
     [exec] 	at java.net.Socket.connect(Socket.java:538)
     [exec] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
     [exec] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
     [exec] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
     [exec] 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
     [exec] 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
     [exec] 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:737)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:650)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:640)
     [exec] 
     [exec] Total time: 0 seconds
     [exec] Result: 1
     [echo] h2: FAIL
```

**Comment by RuiChen08** [comment]
Fixed the junit4.7 broken link https://jaist.dl.sourceforge.net/project/junit/junit/4.7/junit4.7.zip

**Comment by RuiChen08** [comment]
new problem
``` 
    [exec] get-source:
     [exec]      [echo]  "http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar 
     [exec]       [get] Getting: http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar
     [exec]       [get] To: /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/libs/h2/downloads/h2-1.2.123.jar
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar
     [exec]       [get] Error opening connection java.io.FileNotFoundException: http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar
     [exec]       [get] Can't get http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar to /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/libs/h2/downloads/h2-1.2.123.jar
     [exec] 
     [exec] BUILD FAILED
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/bms/common.xml:46: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/libs/libs.xml:90: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/libs/common.xml:24: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/util.xml:31: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/util.xml:51: Can't get http://repo2.maven.org/maven2/com/h2database/h2/1.2.123//h2-1.2.123.jar to /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/libs/h2/downloads/h2-1.2.123.jar
     [exec] 
     [exec] Total time: 7 seconds
     [exec] Result: 1
     [echo] h2: FAIL
```

**Comment by RuiChen08** [comment]
Fixed
