### ISSUE TITLE
sunflow: broken URL

### ISSUE THREAD

**Issue by johnjiabinzhang** [RuiChen08/dacapobench#5]
Building `sunflow` benchmark also has broken URL problem:
```
dacapobench/benchmarks/util.xml:50: java.net.UnknownHostException: softlayer.dl.sourceforge.net
```

Full output:
```
sunflow:
     [exec] Buildfile: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/sunflow/build.xml
     [exec] 
     [exec] incremental:
     [exec] 
     [exec] common.source:
     [exec] 
     [exec] check-source:
     [exec] 
     [exec] get-source:
     [exec]       [get] Getting: http://softlayer.dl.sourceforge.net/sunflow/sunflow-src-v0.07.2.zip
     [exec]       [get] To: /home/johnz/Documents/Work/dacapobench/benchmarks/bms/sunflow/downloads/sunflow-src-v0.07.2.zip
     [exec]       [get] Error getting http://softlayer.dl.sourceforge.net/sunflow/sunflow-src-v0.07.2.zip to /home/johnz/Documents/Work/dacapobench/benchmarks/bms/sunflow/downloads/sunflow-src-v0.07.2.zip
     [exec] 
     [exec] BUILD FAILED
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/bms/common.xml:46: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/bms/common.xml:50: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/util.xml:31: The following error occurred while executing this line:
     [exec] /home/johnz/Documents/Work/dacapobench/benchmarks/util.xml:50: java.net.UnknownHostException: softlayer.dl.sourceforge.net
     [exec] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
     [exec] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
     [exec] 	at java.net.Socket.connect(Socket.java:589)
     [exec] 	at java.net.Socket.connect(Socket.java:538)
     [exec] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
     [exec] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
     [exec] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
     [exec] 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
     [exec] 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
     [exec] 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
     [exec] 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:737)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:650)
     [exec] 	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:640)
     [exec] 
     [exec] Total time: 0 seconds
     [exec] Result: 1
     [echo] sunflow: FAIL

```

**Comment by RuiChen08** [comment]
Fixed
