### ISSUE TITLE
Jython: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by RuiChen08** [RuiChen08/dacapobench#8]
'''
[exec] expose:
     [exec]    [expose] Exposing 180 classes
     [exec] 
     [exec] BUILD FAILED
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/bms/common.xml:46: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/bms/jython/build.xml:47: The following error occurred while executing this line:
     [exec] /home/admin-u5958754/IdeaProject/dacapobench/benchmarks/bms/jython/build/build.xml:578: java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(Lorg/objectweb/asm/ClassReader;I)V
     [exec] 	at org.python.expose.generate.ExposedTypeProcessor.<init>(ExposedTypeProcessor.java:51)
     [exec] 	at org.python.expose.generate.ExposeTask.expose(ExposeTask.java:49)
     [exec] 	at org.python.expose.generate.ExposeTask.process(ExposeTask.java:39)
     [exec] 	at org.python.util.GlobMatchingTask.execute(GlobMatchingTask.java:70)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [exec] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:592)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [exec] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:592)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [exec] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [exec] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
     [exec] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
     [exec] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [exec] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:592)
     [exec] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [exec] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [exec] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [exec] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [exec] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [exec] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     [exec] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [exec] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [exec] 	at org.apache.tools.ant.Main.runBuild(Main.java:857)
     [exec] 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
     [exec] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
     [exec] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
     [exec] 
     [exec] Total time: 11 seconds
     [exec] Result: 1
     [echo] jython: FAIL
'''

**Comment by RuiChen08** [comment]
The NoSuchMethodError javadoc says this:

    Thrown if an application tries to call a specified method of a class (either static or instance), and that class no longer has a definition of that method.

    Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

I am not sure about this. Possible cause:

An incompatibility between the version of ASM required by Hibernate (asm-1.5.3.jar) and the one required by Spring. But, actually, I wonder why you have asm-2.2.3.jar on your classpath (ASM is bundled in spring.jar and spring-core.jar to avoid such problems AFAIK).

or the library is changed.

**Comment by RuiChen08** [comment]
Some notice about jython benchmark:
I have tried to use different version of java to build jython, followings are the result
jdk 1.5.* -> pass 
jdk 1.8.* -> failed (no such method error)
openjdk 8 -> failed (java: return 1)

**Comment by RuiChen08** [comment]
Temporarily closing it.

**Comment by RuiChen08** [comment]
reopen this, after testing. These problems arise when using different jdk.

jdk 1.5.* -> pass
jdk 1.8.* -> failed (no such method error)
openjdk 8 -> failed (NullPointerException)
